### ISSUE TITLE
Determine frame rate

### ISSUE THREAD

**Issue by clarematthews** [jedrichards/video-app#1]
Is it possible to make call to ffmpeg (or equivalent) on file selection, to automatically check and extract frame rate? This is a manual step I have to do every time I load a video.

**Comment by jedrichards** [comment]
Well, ffmpeg is a command line tool, and you don't have access to the command line from a web page. There might be ways to embed ffmpeg on the page though, but potentially quite complex/clunky.

**Comment by jedrichards** [comment]
Okey tried to do this with ffmpeg embedded in the page. But its a bit hacky. See what you think.

**Comment by clarematthews** [comment]
I tried it with a video that has fps 29.97. The FPS in the app got set to 97.00

**Comment by jedrichards** [comment]
Regex issue ... maybe fixed now.
